controller_list:
  - name: fake_arm3_controller
    type: $(arg fake_execution_type)
    joints:
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
      - robot3/joint7
  - name: fake_arm4_controller
    type: $(arg fake_execution_type)
    joints:
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
      - robot4/joint7
  - name: fake_gripper3_controller
    type: $(arg fake_execution_type)
    joints:
      - robot3/gripper
  - name: fake_gripper4_controller
    type: $(arg fake_execution_type)
    joints:
      - robot4/gripper
  - name: fake_arm34_controller
    type: $(arg fake_execution_type)
    joints:
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
      - robot3/joint7
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
      - robot4/joint7
  - name: fake_gripper34_controller
    type: $(arg fake_execution_type)
    joints:
      - robot3/gripper
      - robot4/gripper
initial:  # Define initial robot poses per group
  - group: arm3
    pose: zero
  - group: arm4
    pose: zero
  - group: gripper3
    pose: init
  - group: gripper4
    pose: init
  - group: arm34
    pose: rest
  - group: gripper34
    pose: init