robot1/joint1: # 200-s500
  ID: 25
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot1/joint2: # 200-s500
  ID: 26
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Min_Position_Limit: -319534
  Max_Position_Limit: 319534
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot1/joint3: # 100-s500
  ID: 27
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Homing_Offset: -125480
  #Current_Limit: 15900
robot1/joint4: # 100-s500
  ID: 28
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  #Current_Limit: 15900
robot1/joint5: # 20-S300
  ID: 29
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  #Current_Limit: 4500
robot1/joint6: # 20-S300
  ID: 30
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  #Current_Limit: 4500
robot1/gripper: # RH-P12-RN(A)
  ID: 181
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Current_Limit: 1984