robot1/joint1: # 200-s500
  ID: 25
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Current_Limit:  22740 	
robot1/joint2: # 200-s500
  ID: 26
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Current_Limit: 22740
robot1/joint3: # 100-s500
  ID: 27
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Homing_Offset: -125480
  Current_Limit: 15900
robot1/joint4: # 100-s500
  ID: 28
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Current_Limit: 15900
robot1/joint5: # 20-S300
  ID: 29
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Current_Limit: 4500
robot1/joint6: # 20-S300
  ID: 30
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Current_Limit: 4500
robot1/gripper: # RH-P12-RN(A)
  ID: 181
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Current_Limit: 1984

robot2/joint1:
  ID: 92
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot2/joint2:
  ID: 93
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -319534
  Max_Position_Limit: 319534
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot2/joint3:
  ID: 94
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot2/joint4:
  ID: 95
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Homing_Offset: -125480
  Min_Position_Limit: -501923
  Max_Position_Limit:  226869 #223076
robot2/joint5:
  ID: 96
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1000
  Min_Position_Limit: -439182
  Max_Position_Limit: 439182
robot2/joint6:
  ID: 97
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -151875
  Max_Position_Limit: 151875
robot2/joint7:
  ID: 98
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot2/gripper:
  ID: 162
  Return_Delay_Time: 25
  Operating_Mode: 5
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Current_Limit: 1984
