robot2/joint1:
  ID: 92
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot2/joint2:
  ID: 93
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Min_Position_Limit: -319534
  Max_Position_Limit: 319534
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot2/joint3:
  ID: 94
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot2/joint4:
  ID: 95
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Homing_Offset: -125480
  Min_Position_Limit: -501923
  Max_Position_Limit:  226869 #223076
robot2/joint5:
  ID: 96
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Min_Position_Limit: -439182
  Max_Position_Limit: 439182
robot2/joint6:
  ID: 97
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Min_Position_Limit: -151875
  Max_Position_Limit: 151875
robot2/joint7:
  ID: 98
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot2/gripper:
  ID: 162
  Return_Delay_Time: 25
  Operating_Mode: 5
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Current_Limit: 1984
