robot1/joint1:
  ID: 61
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 500
  Profile_Velocity: 2900
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot1/joint2:
  ID: 62
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 500
  Profile_Velocity: 2900
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
  Min_Position_Limit: -319535
  Max_Position_Limit: 319535
robot1/joint3:
  ID: 63
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 500
  Profile_Velocity: 2900
  Homing_Offset: -125480
  Min_Position_Limit: -501668
  Max_Position_Limit: 250961
robot1/joint4:
  ID: 64
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
  Min_Position_Limit: -439182
  Max_Position_Limit: 439182
robot1/joint5:
  ID: 65
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 500
  Profile_Velocity: 2900
  Min_Position_Limit: -151875
  Max_Position_Limit: 151875
robot1/joint6:
  ID: 66
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robot1/gripper:
  ID: 131
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Current_Limit: 600
  Profile_Acceleration: 9982
  Profile_Velocity: 2900