robot3/joint1:
  ID: 92
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot3/joint2:
  ID: 93
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -319534
  Max_Position_Limit: 319534
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000 
robot3/joint3:
  ID: 94
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot3/joint4:
  ID: 95
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Homing_Offset: -125480
  Min_Position_Limit: -501923
  Max_Position_Limit:  226869 #223076
robot3/joint5:
  ID: 96
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1000
  Min_Position_Limit: -439182
  Max_Position_Limit: 439182
robot3/joint6:
  ID: 97
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -151875
  Max_Position_Limit: 151875
robot3/joint7:
  ID: 98
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot3/gripper:
  ID: 162
  Return_Delay_Time: 25
  Operating_Mode: 5
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2500
  Current_Limit: 1700
  Goal_Current: 600

robot4/joint1:
  ID: 99
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot4/joint2:
  ID: 100
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -319534
  Max_Position_Limit: 319534
  Position_P_Gain: 850
  Position_D_Gain: 0
  Position_I_Gain: 300
  Velocity_P_Gain: 27000
  Velocity_I_Gain: 30000
robot4/joint3:
  ID: 101
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot4/joint4:
  ID: 102
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Homing_Offset: -125480
  Min_Position_Limit: -501923
  Max_Position_Limit:  226869 #223076
robot4/joint5:
  ID: 103
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1000
  Min_Position_Limit: -439182
  Max_Position_Limit: 439182
robot4/joint6:
  ID: 104
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -151875
  Max_Position_Limit: 151875
robot4/joint7:
  ID: 105
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot4/gripper:
  ID: 172
  Return_Delay_Time: 25
  Operating_Mode: 5
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2500
  Current_Limit: 1700
  Goal_Current: 600