arm3_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot3/joint1
    - robot3/joint2
    - robot3/joint3
    - robot3/joint4
    - robot3/joint5
    - robot3/joint6
    - robot3/joint7
  gains:
    robot3/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm4_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot4/joint1
    - robot4/joint2
    - robot4/joint3
    - robot4/joint4
    - robot4/joint5
    - robot4/joint6
    - robot4/joint7
  gains:
    robot4/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot4/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot4/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot4/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot4/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot4/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot4/joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot3/gripper
  gains:
    robot3/gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot4/gripper
  gains:
    robot4/gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1