robot1/joint1:
  ID: 8
  Return_Delay_Time: 1
  Homing_Offset: 1024
  Operating_Mode: 0
  Torque_Enable: 1
robot1/joint2:
  ID: 9
  Return_Delay_Time: 1
  Homing_Offset: 2048
  Operating_Mode: 0
  Torque_Enable: 1
robot1/joint3:
  ID: 10
  Return_Delay_Time: 1
  Homing_Offset: 2048
  Operating_Mode: 0
  Torque_Enable: 1
robot1/joint4:
  ID: 11
  Return_Delay_Time: 1
  Homing_Offset: 1024
  Operating_Mode: 0
  Torque_Enable: 1
robot1/joint5:
  ID: 12
  Return_Delay_Time: 1
  Homing_Offset: 2048
  Operating_Mode: 0
  Torque_Enable: 1
robot1/joint6:
  ID: 13
  Return_Delay_Time: 1
  Homing_Offset: 2048
  Operating_Mode: 0
  Torque_Enable: 0
robot1/joint7:
  ID: 14
  Return_Delay_Time: 1
  Homing_Offset: 2048
  Operating_Mode: 0
  Torque_Enable: 0
robot1/gripper:
  ID: 121
  Return_Delay_Time: 1
  Homing_Offset: 1024
  Operating_Mode: 0
  Torque_Enable: 1
