# robot3/joint1:
#   ID: 85
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 2000
#   Profile_Velocity: 1000
# robot3/joint2:
#   ID: 86
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 2000
#   Profile_Velocity: 1000
#   Min_Position_Limit: -319534
#   Max_Position_Limit: 319534
# robot3/joint3:
#   ID: 87
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 2000
#   Profile_Velocity: 1000
# robot3/joint4:
#   ID: 88
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 2000
#   Profile_Velocity: 1000
#   Homing_Offset: -125480
#   Min_Position_Limit: -501923
#   Max_Position_Limit:  226869 #223076
# robot3/joint5:
#   ID: 89
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 1000
#   Min_Position_Limit: -439182
#   Max_Position_Limit: 439182
# robot3/joint6:
#   ID: 90
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 2000
#   Profile_Velocity: 1000
#   Min_Position_Limit: -151875
#   Max_Position_Limit: 151875
# robot3/joint7:
#   ID: 91
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 2000
#   Profile_Velocity: 1000
# robot3/gripper:
#   ID: 152
#   Return_Delay_Time: 25
#   Operating_Mode: 5
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 9982
#   Profile_Velocity: 2500
#   Current_Limit: 800
#   Goal_Current: 150

robot3/joint1:
  ID: 92
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot3/joint2:
  ID: 93
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -319534
  Max_Position_Limit: 319534
robot3/joint3:
  ID: 94
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot3/joint4:
  ID: 95
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Homing_Offset: -125480
  Min_Position_Limit: -501923
  Max_Position_Limit:  226869 #223076
robot3/joint5:
  ID: 96
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1000
  Min_Position_Limit: -439182
  Max_Position_Limit: 439182
robot3/joint6:
  ID: 97
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
  Min_Position_Limit: -151875
  Max_Position_Limit: 151875
robot3/joint7:
  ID: 98
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 2000
  Profile_Velocity: 1000
robot3/gripper:
  ID: 162
  Return_Delay_Time: 25
  Operating_Mode: 5
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2500
  Current_Limit: 1200
  Goal_Current: 900