arm1_grav_compensation:
  type: papras_table/GravityCompensationController
  joint_names:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
    - robot1/joint7
    - robot1/gripper

  root_link: robot1/base_link
  tip_link: robot1/trigger

arm2_grav_compensation:
  type: papras_table/GravityCompensationController
  joint_names:
    - robot2/joint1
    - robot2/joint2
    - robot2/joint3
    - robot2/joint4
    - robot2/joint5
    - robot2/joint6
    - robot2/joint7
    - robot2/gripper

  root_link: robot2/base_link
  tip_link: robot2/trigger

arm3_grav_compensation:
  type: papras_table/GravityCompensationController
  joint_names:
    - robot3/joint1
    - robot3/joint2
    - robot3/joint3
    - robot3/joint4
    - robot3/joint5
    - robot3/joint6

  root_link: robot3/base_link
  tip_link: robot3/trigger

arm1_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
      - robot1/joint1
      - robot1/joint2
