robot1/joint1:
  ID: 1
  Return_Delay_Time: 25
  Homing_Offset: -1024

robot1/joint2:
  ID: 2
  Return_Delay_Time: 25
  Homing_Offset: 0

robot1/joint3:
  ID: 3
  Return_Delay_Time: 25
  Homing_Offset: 0
  # Homing_Offset: -125480

robot1/joint4:
  ID: 4
  Return_Delay_Time: 25
  Homing_Offset: -1024


robot1/joint5:
  ID: 5
  Return_Delay_Time: 25
  Homing_Offset: 0

robot1/joint6:
  ID: 6
  Return_Delay_Time: 25
  Homing_Offset: 0

robot1/joint7:
  ID: 7
  Return_Delay_Time: 25
  Homing_Offset: 0

robot1/gripper:
  ID: 8
  Return_Delay_Time: 25
  Homing_Offset: 0