joints:
  - 'robot1/joint1'
  - 'robot1/joint2'
  - 'robot1/joint3'
  - 'robot1/joint4'
  - 'robot1/joint5'
  - 'robot1/joint6'
  - 'robot1/gripper'

# gripper_joint: 'robot1/rh_r1_joint'
limb_names:
  - 'robot1'
eef_links:
  - 'robot1/end_effector_link'
gripper_homing_position: 0.0
max_effort: 1.0
init_pose: [0.0, 0.6122, 2.2, -1.0, 0.0, -1.4177, 0.0, 0.0]
Kp_follower_feedback: [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]
Kp_nullspace_feedback: [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]
Kp_base_pose_feedback: [0.05,0.025,0.05,0.05,0.05,0.05,0.025,0.05,0.025,0.05,0.05,0.05,0.05,0.025]
