joints:
  - 'robot1/joint1'
  - 'robot1/joint2'
  - 'robot1/joint3'
  - 'robot1/joint4'
  - 'robot1/joint5'
  - 'robot1/joint6'
  - 'robot1/joint7'
  - 'robot1/gripper'
limb_names:
  - 'robot1'
eef_links:
  - 'robot1/end_effector_link'
max_effort: 1.0
init_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.0]
Kp_follower_feedback: [0.1,0.1,0.1,0.1,0.1,0.1,0.1, 0.5]
Kp_nullspace_feedback: [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]
Kp_base_pose_feedback: [0.02,0.01,0.02,0.02,0.02,0.02,0.01,0.01]
